# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pushnotification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pushnotification
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Alamofire'
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  
  # log in with facebook
  pod 'FBSDKLoginKit'
  
  #Google Sign IN
  pod 'GoogleSignIn'

end
